# Generated by Django 4.1.5 on 2023-01-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('member_since', models.DateField()),
                ('name', models.CharField(max_length=50)),
                ('image', models.CharField(max_length=300)),
            ],
        ),
    ]
