# Generated by Django 4.1.5 on 2023-01-10 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discotifyapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=50)),
                ('album_name', models.CharField(max_length=50)),
                ('record_image', models.CharField(max_length=300)),
                ('release_date', models.DateField()),
                ('spotify', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discotifyapi.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discotifyapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_user', to='discotifyapi.user')),
                ('tradee_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_album', to='discotifyapi.album')),
                ('trader_album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_album', to='discotifyapi.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_user', to='discotifyapi.user')),
            ],
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=50)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discotifyapi.album')),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discotifyapi.genre'),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discotifyapi.user'),
        ),
    ]
